/**
 * The curriculum. Each lesson states its target picture as eight rows — that is
 * the specification, written by hand — plus a reference solution that must draw
 * it. `par` is the reference solution's measured command count, locked by the
 * test suite so it cannot drift.
 *
 * Adding a lesson is one object. `requires` names mnemonics the solution must
 * use, for lessons that teach a specific instruction rather than a shape.
 */
export interface Lesson {
  id: string;
  title: string;
  language: 'blocks' | 'assembly';
  teaches: string;
  brief: string;
  hint?: string;
  starter: string;
  /** Eight rows of eight: '.' off, 'B' blue, 'R' red, 'Y' yellow. */
  target: string[];
  solution: string;
  /**
   * Commands in the reference solution — what the learner types, not cycles the
   * machine runs. A REPEAT counts as one command plus its body. Measured, then
   * locked by the suite.
   */
  par: number;
  requires?: string[];
}

const empty = (rows: string[]): string[] => [
  ...rows,
  ...Array(8 - rows.length).fill('........'),
];

export const LESSONS: Lesson[] = [
  {
    id: 'first-fill',
    title: 'Your first pixels',
    language: 'blocks',
    teaches: 'instructions run in order, one after another',
    brief: 'Paint the first three cells.',
    starter: 'FILL 1',
    target: empty(['BBB.....']),
    solution: 'FILL 3',
    par: 1,
  },
  {
    id: 'skipping',
    title: 'Leave a gap',
    language: 'blocks',
    teaches: 'SKIP moves the pen without painting',
    brief: 'Two pairs, with a gap between them.',
    hint: 'SKIP moves without leaving anything behind.',
    starter: 'FILL 2',
    target: empty(['BB..BB..']),
    solution: 'FILL 2 SKIP 2 FILL 2',
    par: 3,
  },
  {
    id: 'going-down',
    title: 'Going down',
    language: 'blocks',
    teaches: 'ROW is the only way to the next line',
    brief: 'Four on the top row, four on the next — opposite ends.',
    hint: 'ROW always moves down one line, whatever column you are in.',
    starter: 'FILL 4\nROW',
    target: empty(['BBBB....', '....BBBB']),
    solution: 'FILL 4 ROW SKIP 4 FILL 4',
    par: 4,
  },
  {
    id: 'repeating',
    title: 'Do it again',
    language: 'blocks',
    teaches: 'REPEAT runs a block of commands over and over',
    brief: 'Four stripes. Write it once, not four times.',
    hint: 'A full row of FILL leaves the pen at the start of the next line.',
    starter: 'FILL 8\nROW',
    target: [
      'BBBBBBBB',
      '........',
      'BBBBBBBB',
      '........',
      'BBBBBBBB',
      '........',
      'BBBBBBBB',
      '........',
    ],
    solution: 'REPEAT 4 [ FILL 8 ROW ]',
    par: 3,
  },
  {
    id: 'first-store',
    title: 'One pixel, by hand',
    language: 'assembly',
    teaches: 'the screen is memory; STORE writes a colour to an address',
    brief: 'Paint the top-left cell blue, in assembly this time.',
    hint: 'R0 holds the address. R2 holds the colour. STORE writes one into the other.',
    starter: 'LOAD R0, 0\nHALT',
    target: empty(['B.......']),
    solution: 'LOAD R0, 0\nLOAD R2, BLUE\nSTORE R2, [R0]\nHALT',
    par: 4,
    requires: ['STORE'],
  },
  {
    id: 'moving',
    title: 'Move the cursor',
    language: 'assembly',
    teaches: 'ADDI changes a register, and the address register is the pen',
    brief: 'Three cells in a row.',
    hint: 'Nothing moves on its own. Add one to the address between stores.',
    starter: 'LOAD R0, 0\nLOAD R2, BLUE\nSTORE R2, [R0]\nHALT',
    target: empty(['BBB.....']),
    solution: [
      'LOAD R0, 0',
      'LOAD R2, BLUE',
      'STORE R2, [R0]',
      'ADDI R0, 1',
      'STORE R2, [R0]',
      'ADDI R0, 1',
      'STORE R2, [R0]',
      'HALT',
    ].join('\n'),
    par: 8,
    requires: ['ADDI'],
  },
  {
    id: 'three-inks',
    title: 'Three inks',
    language: 'assembly',
    teaches: 'cell values are colours: 1 blue, 2 red, 3 yellow',
    brief: 'Blue, red, yellow — one of each, side by side.',
    starter: 'LOAD R0, 0\nLOAD R2, BLUE\nSTORE R2, [R0]\nHALT',
    target: empty(['BRY.....']),
    solution: [
      'LOAD R0, 0',
      'LOAD R2, BLUE',
      'STORE R2, [R0]',
      'ADDI R0, 1',
      'LOAD R2, RED',
      'STORE R2, [R0]',
      'ADDI R0, 1',
      'LOAD R2, YELLOW',
      'STORE R2, [R0]',
      'HALT',
    ].join('\n'),
    par: 10,
  },
  {
    id: 'first-loop',
    title: 'Your first loop',
    language: 'assembly',
    teaches: 'a loop is a counter, a subtraction, and a jump',
    brief: 'The whole top row — without writing eight stores.',
    hint: 'Count down in a register. JNZ jumps while that register is not zero.',
    starter: 'LOAD R0, 0\nLOAD R1, 8\nLOAD R2, BLUE\nHALT',
    target: empty(['BBBBBBBB']),
    solution: [
      'LOAD R0, 0',
      'LOAD R1, 8',
      'LOAD R2, BLUE',
      'loop: STORE R2, [R0]',
      'ADDI R0, 1',
      'SUBI R1, 1',
      'JNZ R1, loop',
      'HALT',
    ].join('\n'),
    par: 8,
    requires: ['JNZ', 'SUBI'],
  },
  {
    id: 'down-the-side',
    title: 'Down the side',
    language: 'assembly',
    teaches: 'the screen is eight wide, so adding eight moves straight down',
    brief: 'The whole left-hand column.',
    hint: 'Same loop as before. Only the step changes.',
    starter: 'LOAD R0, 0\nLOAD R1, 8\nLOAD R2, RED\nHALT',
    target: Array(8).fill('R.......'),
    solution: [
      'LOAD R0, 0',
      'LOAD R1, 8',
      'LOAD R2, RED',
      'loop: STORE R2, [R0]',
      'ADDI R0, 8',
      'SUBI R1, 1',
      'JNZ R1, loop',
      'HALT',
    ].join('\n'),
    par: 8,
  },
  {
    id: 'diagonal',
    title: 'Corner to corner',
    language: 'assembly',
    teaches: 'combining strides — nine is one across and one down',
    brief: 'A diagonal, top-left to bottom-right.',
    hint: 'One right is +1. One down is +8.',
    starter: 'LOAD R0, 0\nLOAD R1, 8\nLOAD R2, YELLOW\nHALT',
    target: [
      'Y.......',
      '.Y......',
      '..Y.....',
      '...Y....',
      '....Y...',
      '.....Y..',
      '......Y.',
      '.......Y',
    ],
    solution: [
      'LOAD R0, 0',
      'LOAD R1, 8',
      'LOAD R2, YELLOW',
      'loop: STORE R2, [R0]',
      'ADDI R0, 9',
      'SUBI R1, 1',
      'JNZ R1, loop',
      'HALT',
    ].join('\n'),
    par: 8,
  },
  {
    id: 'nested-loops',
    title: 'A loop inside a loop',
    language: 'assembly',
    teaches: 'nesting loops, and keeping two counters apart',
    brief: 'A four-by-four block in the top-left corner.',
    hint: 'One loop walks a row. Another loop runs that loop four times.',
    starter: 'LOAD R0, 0\nLOAD R2, BLUE\nHALT',
    target: empty(['BBBB....', 'BBBB....', 'BBBB....', 'BBBB....']),
    solution: [
      'LOAD R0, 0',
      'LOAD R2, BLUE',
      'LOAD R1, 4',
      'row: LOAD R3, 4',
      'cell: STORE R2, [R0]',
      'ADDI R0, 1',
      'SUBI R3, 1',
      'JNZ R3, cell',
      'ADDI R0, 4',
      'SUBI R1, 1',
      'JNZ R1, row',
      'HALT',
    ].join('\n'),
    par: 12,
  },
  {
    id: 'test-at-the-top',
    title: 'Test at the top',
    language: 'assembly',
    teaches: 'JZ and JMP build a loop that checks before it runs',
    brief: 'Six cells across the top.',
    hint: 'JZ leaves the loop when the counter hits zero. JMP goes back to the check.',
    starter: 'LOAD R0, 0\nLOAD R1, 6\nLOAD R2, RED\nHALT',
    target: empty(['RRRRRR..']),
    solution: [
      'LOAD R0, 0',
      'LOAD R1, 6',
      'LOAD R2, RED',
      'check: JZ R1, done',
      'STORE R2, [R0]',
      'ADDI R0, 1',
      'SUBI R1, 1',
      'JMP check',
      'done: HALT',
    ].join('\n'),
    par: 9,
    requires: ['JZ', 'JMP'],
  },
  {
    id: 'registers-as-numbers',
    title: 'Numbers in registers',
    language: 'assembly',
    teaches: 'ADD and SUB work register-to-register, not just on constants',
    brief: 'The top row again — but the step lives in a register.',
    hint: 'Put 1 in a spare register and use ADD and SUB instead of ADDI and SUBI.',
    starter: 'LOAD R3, 1\nLOAD R0, 0\nLOAD R1, 8\nLOAD R2, YELLOW\nHALT',
    target: empty(['YYYYYYYY']),
    solution: [
      'LOAD R3, 1',
      'LOAD R0, 0',
      'LOAD R1, 8',
      'LOAD R2, YELLOW',
      'loop: STORE R2, [R0]',
      'ADD R0, R3',
      'SUB R1, R3',
      'JNZ R1, loop',
      'HALT',
    ].join('\n'),
    par: 9,
    requires: ['ADD', 'SUB'],
  },
  {
    id: 'reading-the-screen',
    title: 'Reading the screen',
    language: 'assembly',
    teaches: 'LOADI reads a cell back, and MOV copies one register to another',
    brief: 'Paint the corner red, then read that colour back and use it further down.',
    hint: 'LOADI puts what is at an address into a register. MOV copies it to the pen.',
    starter: 'LOAD R0, 0\nLOAD R2, RED\nSTORE R2, [R0]\nHALT',
    target: empty(['R.......', '.R......']),
    solution: [
      'LOAD R0, 0',
      'LOAD R2, RED',
      'STORE R2, [R0]',
      'LOADI R1, [R0]',
      'MOV R2, R1',
      'LOAD R0, 9',
      'STORE R2, [R0]',
      'HALT',
    ].join('\n'),
    par: 8,
    requires: ['LOADI', 'MOV'],
  },
];
